### PR TITLE
make iat field epoch time

### PR DESCRIPTION
**Pull request by dagda1**
## Motivation

The iat field in both the idToken and the accessToken issued from `/oauth/token` is not currently in unix timestamp format.

## Approach

Convert iat field into a unix timestamp.

### CODE REVIEW

**Review by taras — COMMENTED** [review]
It looks good, but diff is bigger than I would expect. Does it need a package-lock.json updated?

**Comment by dagda1** [comment]
> It looks good, but diff is bigger than I would expect. Does it need a package-lock.json updated?

I've reverted it

**Review by taras — APPROVED** [review]
👍

**Comment by taras** [comment]
Merge at your leisure

**Pull request merged**
