### PR TITLE
Foundation Simulator

### PR DESCRIPTION
**Pull request by jbolda**
## Motivation

We want to improve the ability to iteratively build a simulator for use in published simulators in this repository or custom implementations elsewhere. This includes the components likely to be used in each simulator (server, router, data store) and pieces to enable quickly spinning up a simulator to get started.

### CODE REVIEW

**Comment by frontsidejack** [comment]
### Package Changes Through 1f602fa45f299efcba38d6ef3c5380e8d21c1847
No changes.

**Comment by frontsidejack** [comment]
The following preview packages have been published by Covector:
- `@simulacrum/foundation-simulator@0.0.1-foundation-simulator.3071942`

<p align="right">3071942</p>

**Comment by cowboyd** [comment]
I had a brief look over the code. I think having some tests that demonstrate how you would use the foundation simulator Api, and especially how you would interact with the store would serve as good documentation, as well as a quality control.

**Review by cowboyd — APPROVED** [review]
This looks good, and I don't see why we shouldn't iterate forward on this.

**Pull request merged**
